Repository suzuki-shunsuke/pinact-action, pull requests merged in 2025-03, with the labels that each got.

#568 feat: remove dependency on ghcp and pinact
  .github/workflows/wc-test.yaml
  README.md
  action.yaml
  aqua/aqua-checksums.json
  aqua/imports/ghcp.yaml
Labels: enhancement

#570 docs: update
  README.md
Labels: documentation

#572 docs: update example
  README.md
Labels: documentation

#574 fix: Do not fail if no action.yaml
  action.yaml
Labels: bug

#598 fix: update pinact to v2.0.0
  action.yaml
  aqua/aqua-checksums.json
  aqua/imports/pinact.yaml
Labels: breaking change

#614 ci: Replace autofix-ci/action with suzuki-shunsuke/autofix-ci-action
  .github/workflows/autofix.yaml
Labels: replace-autofix-ci-action
